SETTINGS = {
  places: [
    'Hawaii',
    'New York, New York',
    'Remote',
    'San Francisco Bay Area, CA',
  ],

  positions: ['Software Engineer'],
    # 'Web Developer',
    # 'Software Developer',
    # 'Ruby on Rails'
  # ],

  position_exclusions: [
    ' it ',
    ' sr ',
    '2020',
    'analyst',
    'angular',
    'aws',
    'c#',
    'c++',
    'cloud',
    'contract',
    'contractor',
    'data',
    'data scientist',
    'database',
    'devops',
    'dot',
    'game',
    'instructor',
    'ios',
    'java',
    'lead',
    'machine learning',
    'mapping',
    'net',
    'ops',
    'php',
    'principal',
    'python',
    'scala',
    'senior',
    'scientist',
    'sr.',
    'staff',
    'teacher',
    'teaching',
    'wordpress',
  ],

  good_keywords: {
    'app academy' => 100,
    'appacademy' => 100,
    'apprentice' => 5,
    'beer' => 5,
    'boot camp' => 50,
    'bootcamp' => 50,
    'css' => 5,
    'culture' => 5,
    'cypress' => 5,
    'enzyme' => 5,
    'equity' => 5,
    'html' => 5,
    'javascript' => 10,
    'jest' => 5,
    'jquery' => 10,
    'jr' => 5,
    'junior' => 5,
    'learn' => 5,
    'learning' => 5,
    'mentor' => 5,
    'mentorship' => 5,
    'mysql' => 5,
    'new grad' => 10,
    'new graduates' => 10,
    'postgres' => 5,
    'postgresql' => 5,
    'rails' => 10,
    'react' => 10,
    'redux' => 10,
    'relocation' => 10,
    'ruby' => 10,
    'stock' => 5,
    'unlimited pto' => 10,
    'web developer' => 5,
    'web development' => 5,
  },

  bad_keywords: {
    '2020' => -100,
    'android' => -100,
    'block chain' => -100,
    'blockchain' => -100,
    'crypto' => -100,
    'ios' => -100,
    'phd' => -100,
    'verba' => -100,
    'vitalsource' => -100,
  },

  passing_points: 50,
  simple_output: true
}
